USE [master]
GO

/****** Object:  Database [Shop]    Script Date: 13.12.2023 19:18:06 ******/
CREATE DATABASE [Shop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Shop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Shop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Shop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Shop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Shop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Shop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Shop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Shop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Shop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Shop] SET ARITHABORT OFF 
GO

ALTER DATABASE [Shop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Shop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Shop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Shop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Shop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Shop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Shop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Shop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Shop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Shop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Shop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Shop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Shop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Shop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Shop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Shop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Shop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Shop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Shop] SET  MULTI_USER 
GO

ALTER DATABASE [Shop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Shop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Shop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Shop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Shop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Shop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Shop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Shop] SET  READ_WRITE 
GO

